name: CI

on: [push]

jobs:
  build_and_test_linux:
    strategy:
     matrix:
        platform: [ubuntu-18.04]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install dependencies (Ubuntu 18.04)
      if: matrix.platform == 'ubuntu-18.04'
      run: |
        sudo apt install -y git cmake make gcc g++ libssl-dev libreadline-dev # mgconsole deps
        sudo apt install -y libpython3.7 python3-pip # memgraph deps
        mkdir ~/memgraph
        curl -L https://memgraph.com/download/memgraph/v1.4.0/ubuntu-18.04/memgraph_1.4.0-community-1_amd64.deb > ~/memgraph/memgraph_1.4.0-community-1_amd64.deb
        sudo systemctl mask memgraph
        sudo dpkg -i ~/memgraph/memgraph_1.4.0-community-1_amd64.deb

    - name: Download mgclient
      uses: actions/checkout@master
      with:
        repository: memgraph/mgclient
        ref: 'v1.2.0'
    - name: Install mgclient
      run: |
        mkdir build
        cd build
        cmake ..
        make
        sudo make install

    - uses: actions/checkout@v1
    - name: Install and test mgconsole
      run: |
        mkdir build
        cd build
        cmake ..
        make
        sudo make install
        ctest

  build_apple:
    strategy:
      matrix:
        platform: [macos-10.15]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Download mgclient
        uses: actions/checkout@master
        with:
          repository: memgraph/mgclient
          ref: 'v1.2.0'

      - name: Install mgclient
        run: |
          mkdir build
          cd build
          cmake -DOPENSSL_ROOT_DIR="$(ls -td -- /usr/local/Cellar/openssl@1.1/* | head -n 1)" ..
          make
          sudo make install

      - name: Set-up mgconsole
        uses: actions/checkout@v2

      - name: Build mgconsole
        run: |
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
